import fs from "fs";
import path from "path";
import { S3Client, ListObjectsV2Command } from "@aws-sdk/client-s3";

// Load .env.local
try {
  const envConfig = fs.readFileSync('.env.local', 'utf-8');
  envConfig.split('\n').forEach(line => {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();
      if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
      process.env[key] = value;
    }
  });
} catch (e) {
  // .env.local not found, ignore
}

// Configure S3 client
const region = process.env.AWS_REGION || "ap-southeast-1";
const bucketName = process.env.AWS_S3_BUCKET || "angeloramos.com";

const s3Client = new S3Client({ region });

const ALBUMS_FILE = "src/resources/albums.ts";
const IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".avif"];

async function syncAlbumsFromS3() {
  console.log(`📡 Fetching albums from S3 bucket: ${bucketName}...`);

  try {
    // Step 1: List all top-level folders (albums)
    const folderCommand = new ListObjectsV2Command({
      Bucket: bucketName,
      Delimiter: "/",
    });
    const { CommonPrefixes } = await s3Client.send(folderCommand);

    if (!CommonPrefixes || CommonPrefixes.length === 0) {
      console.log("No album folders found in S3.");
      return;
    }

    console.log(`📁 Found ${CommonPrefixes.length} albums.`);

    const albums = [];

    // Step 2: For each folder, list all images inside
    for (const prefix of CommonPrefixes) {
      const folderName = prefix.Prefix.replace(/\/$/, ""); // Remove trailing slash
      console.log(`  📂 Scanning: ${folderName}`);

      let images = [];
      let isTruncated = true;
      const listCommand = new ListObjectsV2Command({
        Bucket: bucketName,
        Prefix: prefix.Prefix,
      });

      while (isTruncated) {
        const { Contents, IsTruncated, NextContinuationToken } = await s3Client.send(listCommand);
        if (Contents) {
          for (const item of Contents) {
            const ext = path.extname(item.Key).toLowerCase();
            if (IMAGE_EXTENSIONS.includes(ext)) {
              const src = `https://s3.${region}.amazonaws.com/${bucketName}/${encodeURI(item.Key)}`;
              images.push(src);
            }
          }
        }
        isTruncated = IsTruncated;
        listCommand.input.ContinuationToken = NextContinuationToken;
      }

      if (images.length > 0) {
        albums.push({
          title: folderName,
          cover: images[0],
          images: images,
        });
        console.log(`    ✅ ${images.length} photos`);
      }
    }

    // Step 3: Write albums.ts
    const albumsTs = `// Auto-generated by sync-s3.mjs — DO NOT EDIT MANUALLY
// Last synced: ${new Date().toISOString()}

export type Album = {
  title: string;
  cover: string;
  images: string[];
};

export const albums: Album[] = ${JSON.stringify(albums, null, 2)};
`;

    fs.writeFileSync(ALBUMS_FILE, albumsTs);
    console.log(`\n✅ Wrote ${albums.length} albums (${albums.reduce((t, a) => t + a.images.length, 0)} total photos) to ${ALBUMS_FILE}`);

  } catch (error) {
    console.error("❌ Error fetching from S3:", error.message);
  }
}

syncAlbumsFromS3();
